<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Blog
 * @version    1.3.6
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php $posts = $this->getPosts(); ?>

<div class="title-home">
    <h2><?php echo $this->__('Latest Blog') ?></h2>
</div>

<div class="slider-blog latest-post">
<?php foreach ($posts as $post): ?>
    <div class="item">
		<div class="date-blog">
			<?php $date_create = $post->getCreatedTime();?>
			
			<div class="big-txt">
				<?php 
					$day_blog = date("d",strtotime($date_create));
					echo $day_blog;
				?>
			</div>
			
			<div class="normal-txt">
				<?php 
					$month_blog = date("M",strtotime($date_create));
					echo $month_blog;
				?>
				
				<?php 
					$year_blog = date("Y",strtotime($date_create));
					echo $year_blog;
				?>
			</div>
		</div>
		
		<div class="blog-item-content">
			<div class="image-blog">
				<?php
					$pattern = "/<img .+\/>/";
					$subject = $post->getPostContent();
					$result = preg_match( $pattern, $subject , $matches , PREG_OFFSET_CAPTURE );
					$matched =$matches[0];
					$first_img=$matched[0];
				?>
				
				<a class="img-link" title="<?php echo $post->getTitle(); ?>" href="<?php echo $post->getAddress(); ?>" ><?php echo $first_img;?></a>
			</div>
			
			<div class="info-blog">
				<h2 class="postTitle"><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
				
				<div class="info-post">
					<ul>
						<li class="post-user"><?php echo $this->__("By"); ?> <span class="user-wr"><?php echo $post->getUser(); ?></span></li>
						<li class="post-cat">
							<?php $postCats = $post->getCats(); ?>
							<?php if (!empty($postCats)): ?>
								<?php foreach ($postCats as $data): ?>               
										<a href="<?php echo $data['url']; ?>"><?php echo $data['title']; ?></a> 
								<?php endforeach; ?> 
							<?php endif;?>
						</li>
					</ul>
				</div>

				<div class="postContent">
					<?php $text = str_replace($first_img, '', $post->getPostContent()); 
						//echo $text;
						echo substr($text,1,197) . '...';
					?>
				</div>
				
				<div class="action-post">
					<a class="btn-readmore" title="<?php echo $this->__('Read More')?>" href="<?php echo $post->getAddress(); ?>"><?php echo $this->__('Read More')?></a>
				</div>
			</div>
		</div>

    </div>
<?php endforeach; ?>
</div>

	<script>
		jQuery(document).ready(function($) {
			var post_slider = $(".slider-blog");
			post_slider.owlCarousel({				
				responsive:{
					0:{
						items:1
					},
					480:{
						items:1
					},
					768:{
						items:2
					},
					992:{
						items:2
					},
					1200:{
						items:2
					}
				},
				autoplay:false,
				loop:false,
				nav : true,
				dots: false,
				autoplaySpeed : 500,
				navSpeed : 500,
				dotsSpeed : 500,
				autoplayHoverPause: true,
				margin:30,
			});	  
		});	
	</script>
